### ISSUE TITLE
📋 Feature: File names and tree structure

### ISSUE THREAD

**Issue by stgzach** [samuel-lucas6/Kryptor#11]
**Is your feature request related to a problem? Please describe.**
My problem is that I would like to be able to decrypt a single file from a folder but the names are random. Which is fine.

**Describe the feature you'd like**
But I would like to be able to have a file that has a different type that with the password would allow us to see the encrypted files and their original names and paths. And a function that would allow us in shred/encrypt only the files selected from this list.

**Why should this feature be implemented?**
I think I'm not the only one who would like to be able to encrypt his files and not have to decrypt all of them to open only one file but wants to keep the file name anonymous.

**Comment by samuel-lucas6** [comment]
That's an interesting idea. I'll admit that it's problematic compared to how Cryptomator does things. I can certainly look into doing this for folder encryption in v3.

**Comment by stgzach** [comment]
Thank you very much.

**Comment by samuel-lucas6** [comment]
My current plan is to see what outputting the original and obfuscated file names to the console looks like. Then I can also look into storing all of the file paths in a file without an obfuscated name (e.g. directory structure.txt) that gets encrypted, but that's a lot easier said than done. I think it'll be a bit messy implementing that, and I'm trying to avoid messy/unnecessarily complex code when possible.

I'm afraid I won't be implementing a way of reading in a list of file paths from a file to decrypt. This would be problematic from the perspective of user input because it would require a new console option for example. It would be even more troublesome in the GUI version.

Kryptor v3 will provide noticeably faster folder encryption and an improved method of reading the stored file names, so that should help too. I hope you understand where I'm coming from.

**Comment by samuel-lucas6** [comment]
I'm closing this issue because Kryptor [v3.0.0 Beta](https://github.com/samuel-lucas6/Kryptor/releases/tag/v3.0.0) now writes the original file names in the console. I investigated your suggestion of storing all of the file names in an encrypted file and concluded that it would be a bit awkward to implement.
