### ISSUE TITLE
💻 Support: Incorrect password

### ISSUE THREAD

**Issue by ghost** [samuel-lucas6/Kryptor#14]
### Description
I tried decrypting a folder that I encrypted on another PC but I always get the "Incorrect password/keyfile or this file has been tampered with" for 2/13 files. I had only copy the encrypted folder to a USB and then the other PC and got this (there were 13 files and a total of 4GBs), also when I encrypted a big folder (20GBs) and sent it to the cloud to share it with people they (and me when I tried) got the same error. I guess is a bug or am I doing something wrong?? I am no IT guy just a privacy advocate so if possible explanation for dummies :D

**Comment by samuel-lucas6** [comment]
Hmm. If the password and/or keyfile is correct, then the non-bug explanation would be that the program version is different. There have been some breaking changes with the last few versions, meaning if people are running different versions of the program, they won't be able to decrypt the files. For example, if you encrypted files with v2.2.1 Beta, then you won't be able to decrypt those files with v2.2.2 Beta.

As for the 2/13 files, that sounds like some sort of bug, or the files got corrupted. Have you tried decrypting those files individually? Also are you using the 'Anonymous Rename' feature? I believe there are some bugs with that feature in the current version.

If it is a bug, then it should be resolved this month in the upcoming release (v3 Beta). However, there are going to be breaking changes again because the file format has completely changed.

Thanks for using Kryptor. I hope you haven't lost any files.

**Comment by ghost** [comment]
on one occasion I encrypted and decrypted the files with the same PC after uploading to the cloud maybe a few days appart (windows GUI version). the last one was encrypted on a Linux PC the 2.2.2 GUI version and tried to decrypt on a windows 2.2.2 version too. The Anonymous Rename was always enabled. 
I did tried to decrypt them individually with no success  (BTW there were copies of data so no problem with loosing it just trying to help). I love Kryptor keep up the good work and I hope it is here to stay :)

**Comment by samuel-lucas6** [comment]
I see. That does sound more like a bug.

That's good to hear. Thanks, although you might be upset to hear that I've stopped working on the GUI version. I discuss why on my [blog](https://samuellucas.com/blog/kryptor-v3.html). It's going to be command line only from here on out.

**Comment by ghost** [comment]
NOOOO!! :( I know that it is easier but the GUI is a nice welcome to newcomers to use encryption. It even let you share files with people that know almost nothing about PCs. GG

**Comment by samuel-lucas6** [comment]
> 
> 
> NOOOO!! :( I know that it is easier but the GUI is a nice welcome to newcomers to use encryption. It even let you share files with people that know almost nothing about PCs. GG

I know. The command line version does have more of a learning curve but once you learn the commands you need, it really isn't hard to use. The problem is more with people's perception of the command line and people not being willing to learn. However, I'll admit that being able to drag and drop to select files is great.

I would continue working on a GUI version if it made sense. However, as I said in the blog post, it would be extremely difficult to implement a lot of the features in a GUI format. I also shouldn't be spending as much time as I am on this project. 

Maybe I'll work on a GUI version again in the future, but I can't make any promises. If I was going to, I'd like it to be cross-platform, which would mean learning another programming language. 

Anyway, I'm going to leave it there as this issue has gone a bit off topic.

**Comment by samuel-lucas6** [comment]
Fixed in [v3.0.0 Beta](https://github.com/samuel-lucas6/Kryptor/releases/tag/v3.0.0).
